# Generated by Django 2.2 on 2020-07-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200726_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reading_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='subcategories', to='main.Category'),
        ),
    ]
