# Generated by Django 2.2 on 2020-07-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200727_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Головне зображення'),
        ),
    ]
