# Generated by Django 2.2 on 2020-07-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200729_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='ukr_name',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=511),
        ),
    ]
